# org: zuzatoy
# app: my-first-app


service: serverless


provider:
  name: aws
  runtime: nodejs12.x
  profile: default
  region: ap-southeast-2
  stage: dev

plugins:
    - serverless-offline


functions:
    app:
      handler: src/api/index.handler
      events:
        - http: ANY /
        - http: 'ANY {proxy+}'